openapi: '3.0.3'
info:
  title: Zero Width Shortener
  version: 2.2.0
  contact:
    name: Jonah Snider
    email: jonah@jonah.pw
    url: https://jonah.pw
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: Shorten URLs with invisible spaces.
servers:
  - url: https://api.zws.im/
    description: Production API.
paths:
  /{short}:
    get:
      tags:
        - urls
      description: Retrieve a shortened URL.
      parameters:
        - $ref: '#/components/parameters/ShortenedUrl'
        - in: query
          name: visit
          schema:
            type: boolean
            default: true
          required: false
          description: If you should be redirected to the URL instead of returning it as JSON.
      responses:
        '301':
          description: Redirected to the long URL.
        '404':
          $ref: '#/components/responses/UrlNotFoundError'
        '500':
          $ref: '#/components/responses/Error'
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    $ref: '#/components/schemas/Url'
          description: Long URL returned.
  /{short}/stats:
    get:
      tags:
        - urls
      description: Retrieve usage statistics for a shortened URL.
      parameters:
        - $ref: '#/components/parameters/ShortenedUrl'
      responses:
        '404':
          $ref: '#/components/responses/UrlNotFoundError'
        '500':
          $ref: '#/components/responses/Error'
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    $ref: '#/components/schemas/Url'
                  visits:
                    type: array
                    items:
                      type: string
                      format: date-time
                      example: 2021-02-21T03:58:25.794Z
          description: Long URL returned.
  /:
    post:
      tags:
        - urls
      description: Shorten a URL.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  $ref: '#/components/schemas/Url'
              required:
                - url
      responses:
        '500':
          $ref: '#/components/responses/Error'
        '422':
          $ref: '#/components/responses/AttemptedShortenHostnameError'
        '503':
          $ref: '#/components/responses/UniqueShortIdTimeoutError'
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  short:
                    type: string
                    description: The shortened ID for the URL.
          description: URL shortened.
  /stats:
    get:
      description: Total usage statistics for this instance.
      tags:
        - stats
      responses:
        '500':
          $ref: '#/components/responses/Error'
        '200':
          description: Total usage statistics.
          content:
            application/json:
              schema:
                type: object
                properties:
                  urls:
                    type: integer
                    description: Total number of shortened URLs.
                  visits:
                    type: integer
                    description: Total number of visited shortened URLs.
                required:
                  - urls
                  - visits
  /stats/shields/urls:
    get:
      description: Shields endpoint badge response for total number of URLs shortened.
      tags:
        - stats
        - shields
      responses:
        '500':
          $ref: '#/components/responses/Error'
        '200':
          description: Shields endpoint badge response for total number of URLs shortened.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldsEndpointResponse'
  /stats/shields/visits:
    get:
      description: Shields endpoint badge response for total number of shortened URLs visited.
      tags:
        - stats
        - shields
      responses:
        '500':
          $ref: '#/components/responses/Error'
        '200':
          description: Shields endpoint badge response for total number of shortened URLs visited.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldsEndpointResponse'
components:
  schemas:
    Url:
      type: string
      example: https://jonah.pw
      maxLength: 500
    ShieldsEndpointResponse:
      type: object
      properties:
        schemaVersion:
          type: integer
          enum:
            - 1
        label:
          type: string
        message:
          type: string
        color:
          type: string
      required:
        - schemaVersion
        - label
        - message
        - color
  responses:
    UrlNotFoundError:
      description: The shortened URL couldn't be found.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                enum:
                  - 404
              message:
                type: string
              error:
                type: string
                enum:
                  - Not Found
              code:
                type: string
                enum:
                  - E_URL_NOT_FOUND
            required:
              - statusCode
              - message
              - error
              - code
    AttemptedShortenHostnameError:
      description: You attempted to shorten a URL with the same hostname as this instance.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                enum:
                  - 422
              message:
                type: string
              error:
                type: string
                enum:
                  - Unprocessable Entity
              code:
                type: string
                enum:
                  - E_SHORTEN_HOSTNAME
            required:
              - statusCode
              - message
              - error
              - code
    UniqueShortIdTimeoutError:
      description: A unique short ID couldn't be generated in enough time.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                enum:
                  - 503
              message:
                type: string
              error:
                type: string
                enum:
                  - Service Unavailable
              code:
                type: string
                enum:
                  - E_UNIQUE_SHORT_ID_TIMEOUT
            required:
              - statusCode
              - message
              - error
              - code
    Error:
      description: An error occurred while processing the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                enum:
                  - 500
              message:
                type: string
              error:
                type: string
                enum:
                  - Internal Server Error
            required:
              - statusCode
              - message
              - error
  parameters:
    ShortenedUrl:
      in: path
      name: short
      schema:
        type: string
      required: true
      description: The shortened ID for the URL.
